# Generated by Django 5.2.14 on 2026-05-27 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('sap', 'SAP (Fuel & Procurement)'), ('utility', 'Utility (Electricity)'), ('travel', 'Corporate Travel')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict, help_text='Source-specific configuration')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 - Direct emissions'), (2, 'Scope 2 - Indirect (energy)'), (3, 'Scope 3 - Other indirect')])),
                ('category_type', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('fugitive_emissions', 'Fugitive Emissions'), ('purchased_electricity', 'Purchased Electricity'), ('purchased_steam', 'Purchased Steam'), ('business_travel', 'Business Travel'), ('employee_commuting', 'Employee Commuting'), ('waste_generated', 'Waste Generated'), ('procurement', 'Procurement & Supply Chain')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scope', 'category_type'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('unit_type', models.CharField(choices=[('mass', 'Mass (kg, tonnes)'), ('energy', 'Energy (kWh, MJ)'), ('distance', 'Distance (km, miles)'), ('currency', 'Currency (USD, EUR)'), ('volume', 'Volume (liters, gallons)')], max_length=20)),
                ('conversion_factor_to_base', models.DecimalField(decimal_places=10, help_text='Factor to convert to base unit (e.g., kg for mass)', max_digits=20)),
                ('base_unit_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['unit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('source_reference', models.CharField(help_text='Source of emission factor (e.g., EPA, DEFRA, GHG Protocol)', max_length=255)),
                ('year', models.IntegerField(help_text='Year the factor applies to')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.emissioncategory')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.datasource')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.unit')),
            ],
            options={
                'ordering': ['-year', 'category'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_record_id', models.CharField(help_text='Original ID from source system', max_length=255)),
                ('raw_data', models.JSONField(default=dict, help_text='Original raw data as imported')),
                ('activity_value', models.DecimalField(decimal_places=5, max_digits=20)),
                ('emission_value', models.DecimalField(blank=True, decimal_places=5, help_text='Calculated emissions in tonnes CO2e', max_digits=20, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspicious', 'Flagged Suspicious')], default='pending', max_length=20)),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('import_batch_id', models.CharField(blank=True, max_length=100)),
                ('import_errors', models.TextField(blank=True, help_text='Errors encountered during import')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('flagged_reason', models.TextField(blank=True, help_text='Why record was flagged as suspicious')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.emissioncategory')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.emissionfactor')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_records', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_records', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emissions.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.tenant')),
                ('activity_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='emissions.unit')),
            ],
            options={
                'ordering': ['-period_start', '-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('approve', 'Approved'), ('reject', 'Rejected'), ('flag', 'Flagged'), ('unflag', 'Unflagged')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of uploaded file', max_length=64)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('errors', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.tenant')),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.tenant'),
        ),
        migrations.AddField(
            model_name='emissioncategory',
            name='default_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emissions.unit'),
        ),
        migrations.CreateModel(
            name='PlantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emissions.tenant')),
            ],
            options={
                'ordering': ['plant_code'],
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='datasource',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'period_start'], name='emissions_e_tenant__3e708c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='emissions_e_tenant__5a7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'source'], name='emissions_e_tenant__9bd715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emissioncategory',
            unique_together={('scope', 'category_type')},
        ),
    ]
